before_install:
    - sudo apt update
    - sudo apt-get install build-essential

# safelist
branches:
  only:
  - master

matrix:
  include:
    - language: python
    # command to install dependencies
    install:
        - pip install -r requirements.txt
