dist: trusty
sudo: required
matrix:
  include:
      - language: python
        python:
            - "3.6"
        before_script:
            - pip install -r requirements.txt
      - language:
        node_js:
            - 11.15.0
        before_script:
            - npm install
